export const INIT_GAME = 'INIT_GAME';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const REMOVE_NUMBER = 'REMOVE_NUMBER';
export const ADD_NUMBER = 'ADD_NUMBER';
export const UPDATE_EMPTIES = 'UPDATE_EMPTIES';
export const UPDATE_BEST_SCORE = 'UPDATE_EMPTIES';
export const UPDATE_CURRENT_SCORE = 'UPDATE_EMPTIES';

